import Head from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Result from "../components/Result";

export default function Home() {
  return (
    <>
      <Head>
        <title>IMDB Clone App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* header */}
        <Header />

        {/* navbar */}
        <Navbar />

        {/* result */}
        <Result />
      </main>
    </>
  );
}
