import Head from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Result from "../components/Result";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <>
      <Head>
        <title>IMDB Clone App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* header */}
        <Header />

        {/* navbar */}
        <Navbar />

        {/* result */}
        <Result results={results} />
      </main>
    </>
  );
}

// This gets called on every request
export async function getServerSideProps(context) {
  const genre = context.query.genre || "fetchTrending";

  // Fetch data from external API
  const request = await fetch(
    `https://api.themoviedb.org/3/${requests[genre].url}`
  ).then((res) => res.json());

  // Pass data to the page via props
  return { props: { results: request.results } };
}
